import "./globals.css";
import { Poppins } from "next/font/google";

import { Navbar } from "@/components/home/general/Navbar";
import { Footer } from "@/components/home/general/Footer";
import { Provider } from "@/components/auth/provider";
import { authOptions } from "@/components/uploadthing/imageUpload";
import ClientToaster from "@/components/home/general/ClientToater";
import { getServerSession } from "next-auth";

// Font setup with weights
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

// App metadata
export const metadata = {
  title: "Hymonella - where music matters",
  description: "Generated by create next app",
};

// Root layout
export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased pt-[60px]">
        <Provider session={session}>
          <ClientToaster />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
